name: pildservice_easy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  table_calendar: ^3.0.9
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  smooth_page_indicator: ^1.0.0+2
  camera: ^0.10.5+8
  geolocator: ^10.1.0
  http: ^1.1.2
  flutter_native_splash: ^2.3.9
  path_provider: ^2.1.1
  path: ^1.8.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
